mongo-url: localhost:27017
api-addr: localhost:8080
auth-username: admin
auth-password: example-passwd
#elasticsearch-addr: localhost:9200
identity-public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
identity-location: localhost:8081

